/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutUploader: typeof import('@nutui/nutui-taro')['Uploader']
  }
}
